name: ci
on: [push]

jobs:
  build:
    name: Lint/Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Black
        uses: lgeiger/black-action@master
        with:
          args: ". --check -l 80"
      - name: Pylint
        run: ./manage lint
      - name: Test
        run: ./manage tests
